config/routes.rb
Rails.application.routes.draw do
  root "static_pages#show", page: "home"
  get "/:page" => "static_pages#show"
  get "user/show"

  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users
  namespace :admin do
    resources :users
    resources :subjects
    resources :questions
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  has_many :results, dependent: :destroy
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject
  has_many :answers
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :exam
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :exams
  has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :exams, dependent: :destroy
  validates :name, length: {maximum: 40}
  validates_integrity_of :avatar
  validates_processing_of :avatar

  scope :latest, -> {order created_at: :desc}

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  def self.from_omniauth auth
    where(provider:auth.provider, uid: auth.uid).first_or_create do |user|
      user.email= auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  before_action :load_subject, only: [:edit, :update, :destroy]
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = "Add subject success!"
      redirect_to admin_subjects_path
    else
      render :new
      flash[:danger] = "Add subject failed!"
    end
  end


  def index
    @subjects = Subject.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = "Update Success!"
      redirect_to admin_subjects_path
    else
      flash[:danger] = "Update Failed!"
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] =  "subject_deleted"
    else
      flash[:danger] =  "subject_delete_fail"
    end
    redirect_to admin_subjects_path
  end

  private
  def subject_params
    params.require(:subject).permit :name, :description
  end
  def load_subject
    @subject = Subject.find_by id: params[:id]
    if @subject.nil?
      flash[:danger] = "Subject not found"
      redirect_to admin_subjects_path
    end
  end
  end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  # load_and_authorize_resource
  before_action :authenticate_user!, only: [:index, :destroy]

  def index
    # @users= User.paginate(page: params[:page])
    # binding.pry
  #   if params[:search_user].present?
  #     @users= User.search params[:search_user], page: params[:page],
  #     per: Settings.user.per_page
  #   else
  #     @user= User.latest.page(params[:page]).per Settings.user.per_page
  #   end
  #   @users= User.search params[:search_user]
  # end
    if params[:search_user].present?
      @users = User.where(['name LIKE ?', "%#{params[:search_user]}%"])
    else
      @users= User.paginate(page: params[:page])
    end
  end

  def destroy
    @user= User.find(params[:id])
    # binding.pry
    if @user.destroy
      flash[:success] = @user.name+ "has been deleted!"
    else
      flash[:danger] = @user.name+ "can't be delete!"
    end
    redirect_to admin_users_url
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  layout 'admin_layout'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      render template: "static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/static_pages/#{params[:page]}.html.erb"))
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= User.find(params[:id])
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/subjects_helper.rb
module Admin::SubjectsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title page_title = ""
    base_title = "Simple app"
    page_title.empty? ? base_title : page_title + " | " +base_title
  end 
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/subjects/_subject.html.erb
<tr>
  <td class="text-l"><p><%=subject.name %></p></td>
  <td class="text-l"><%= subject.description %></td>
  <td><%= l subject.created_at, format: :long %></td>
  <td class="text-center">
    <%= link_to edit_admin_subject_path(subject),
                title: "edit subject", class: "underline" do %>
      <span class="glyphicon glyphicon-edit"></span>
    <% end %>
  </td>
  <td class="text-center">
    <%= link_to [:admin, subject], method: :delete, title: "delete subject",
                class: "underline text-danger", data: {confirm: ( "Are you sure?")} do %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>
  </td>
</tr>

app/views/admin/subjects/_subject_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <% render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.label :name %><span class="require"></span>
    <%= f.text_field :name, class: "form-control", required: "required" %>
    <%= f.label :description %>
    <%= f.text_area :description, row: 8, class: "form-control" %>
  </div>
  <%= f.submit (yield :button_text), class: "btn btn-primary btn-submit-form" %>
<% end %>

app/views/admin/subjects/edit.html.erb
<% provide :title, "Edit subject"%>
<% provide :button_text, "Update" %>
<%= render "subject_form" %>

app/views/admin/subjects/index.html.erb
<% provide :title, "Manage subject" %>
<div class="div-add-new">
  <%= link_to "Add New subject", new_admin_subject_path %>
</div>
<div class="col-sm-12 no-padding-right">
  <table class="table table-hover bg-table ls-result text-center">
    <thead class="title_table">
    <tr>
      <th class="text-center tbl-cate-name"><%= "Name" %></th>
      <th class="text-center cate-description"><%= "Description" %></th>
      <th class="text-center create-date"><%= "Create" %></th>
      <th class="text-center opt-edit"><%= "Edit" %></th>
      <th class="text-center opt-delete"><%= "Delete" %></th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: "subject", collection: @subjects, as: :subject %>
    </tbody>
  </table>
<!--  <div class="wrap-paging fix-paging"><%#= will_paginate %></div>-->
</div>

app/views/admin/subjects/new.html.erb
<% provide :title, ("Add Subjects") %>
<% provide :button_text, ("Add") %>
<%= render "subject_form" %>